maintainer       "xforty technologies"
maintainer_email "dking@xforty.com"
license          "Apache 2.0"
description      "Installs a drupal-ready environment"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.0"

depends          "apache2"
depends          "imagemagick"
depends          "iptables"
depends          "mysql"
depends          "php"
depends          "php_module"
depends          "php_pear"
depends          "xforty"
