maintainer       "xforty technologies"
maintainer_email "dking@xforty.com"
license          "Apache 2.0"
description      "Installs a drupal environment"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"

depends          "apache2"
depends          "drush"
depends          "imagemagick"
depends          "iptables"
depends          "mysql"
depends          "php"
depends          "php_curl"
depends          "php_gd"
depends          "php_mysql"
